# Generated by Django 6.0.3 on 2026-03-22 14:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FloodAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('water_level', models.FloatField(verbose_name='Water Level (m)')),
                ('predicted_level', models.FloatField(blank=True, null=True, verbose_name='Predicted Level (m)')),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('watch', 'Watch'), ('warning', 'Warning'), ('emergency', 'Emergency')], default='safe', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(choices=[('ellis_bridge', 'Ellis Bridge'), ('gandhi_bridge', 'Gandhi Bridge'), ('nehru_bridge', 'Nehru Bridge'), ('sardar_bridge', 'Sardar Bridge'), ('vasna_barrage', 'Vasna Barrage')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ph', models.FloatField(blank=True, null=True, verbose_name='pH Level')),
                ('dissolved_oxygen', models.FloatField(blank=True, null=True, verbose_name='Dissolved Oxygen (mg/L)')),
                ('turbidity', models.FloatField(blank=True, null=True, verbose_name='Turbidity (NTU)')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature (°C)')),
                ('bod', models.FloatField(blank=True, null=True, verbose_name='BOD (mg/L)')),
                ('water_level', models.FloatField(blank=True, null=True, verbose_name='Water Level (m)')),
                ('conductivity', models.FloatField(blank=True, null=True, verbose_name='Conductivity (µS/cm)')),
                ('tds', models.FloatField(blank=True, null=True, verbose_name='TDS (mg/L)')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrashDetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(choices=[('ellis_bridge', 'Ellis Bridge'), ('gandhi_bridge', 'Gandhi Bridge'), ('nehru_bridge', 'Nehru Bridge'), ('sardar_bridge', 'Sardar Bridge'), ('vasna_barrage', 'Vasna Barrage')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('trash_class', models.CharField(choices=[('solo', 'Solo Trash'), ('cluster', 'Cluster Trash')], max_length=10)),
                ('confidence', models.FloatField(verbose_name='Confidence Score')),
                ('alert_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('latitude', models.FloatField(default=23.0225)),
                ('longitude', models.FloatField(default=72.5714)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='detections/')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trash Detection Event',
                'verbose_name_plural': 'Trash Detection Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
